function getMenuItemsFromString(inputString) {
	// Regular expression to match divs with class "dijitReset dijitMenuItem"
	const regex = /<div[^>]*class=["'](?:dijitReset\s+dijitMenuItem)["'][^>]*>(.*?)<\/div>/g;

	// Extract the inner content of matching divs
	const res = [];
	let match;

	while ((match = regex.exec(inputString)) !== null) {
		res.push(match[1].trim());
	}

	return res;
}

// const htmlString = `'<div class="dijitReset dijitMenuItem" role="option" item="0" id="dijit_form_FilteringSelect_1_popup0">01 - School of Arts &amp; Sciences</div><div class="dijitReset dijitMenuItem" role="option" item="1" id="dijit_form_FilteringSelect_1_popup1">03 - Military Science</div><div class="dijitReset dijitMenuItem" role="option" item="2" id="dijit_form_FilteringSelect_1_popup2">04 - School of Communication &amp; Info (U)</div><div class="dijitReset dijitMenuItem" role="option" item="3" id="dijit_form_FilteringSelect_1_popup3">05 - Graduate School of Education (U)</div><div class="dijitReset dijitMenuItem" role="option" item="4" id="dijit_form_FilteringSelect_1_popup4">07 - Mason Gross School of the Arts (U)</div><div class="dijitReset dijitMenuItem" role="option" item="5" id="dijit_form_FilteringSelect_1_popup5">09 - School of Social Work (U)</div><div class="dijitReset dijitMenuItem" role="option" item="6" id="dijit_form_FilteringSelect_1_popup6">10 - Bloustein School of Planning (U)</div><div class="dijitReset dijitMenuItem" role="option" item="7" id="dijit_form_FilteringSelect_1_popup7">11 - School of Environmental &amp; Biological Sci</div><div class="dijitReset dijitMenuItem" role="option" item="8" id="dijit_form_FilteringSelect_1_popup8">13 - Grad School of Applied &amp; Prof Psych (U)</div><div class="dijitReset dijitMenuItem" role="option" item="9" id="dijit_form_FilteringSelect_1_popup9">14 - School of Engineering</div><div class="dijitReset dijitMenuItem" role="option" item="10" id="dijit_form_FilteringSelect_1_popup10">30 - Ernest Mario School of Pharmacy (U)</div><div class="dijitReset dijitMenuItem" role="option" item="11" id="dijit_form_FilteringSelect_1_popup11">33 - Rutgers Business School- NB campus (U)</div><div class="dijitReset dijitMenuItem" role="option" item="12" id="dijit_form_FilteringSelect_1_popup12">37 - School of Management &amp; Labor Rel (U)</div><div class="dijitReset dijitMenuItem" role="option" item="13" id="dijit_form_FilteringSelect_1_popup13">77 - School of Nursing - New Brunswick (U)</div><div class="dijitMenuItem dijitMenuNextButton" data-dojo-attach-point="nextButton" role="option" style="display: none;" id="dijit_form_FilteringSelect_1_popup_next">More choices</div></div>'`;
// res = getMenuItemsFromString(htmlString);
// console.log(res);

res = [
	"Major in Accounting (NB)",
	"Major in Global Humanities (NB)",
	"Major in African, Middle Eastern and South Asian Languages and Literatures (AMESALL) - Regional Option (NB)",
	"Major in Africana Studies (NB)",
	"Major in Agriculture and Food Systems (NB)",
	"Major in Agriculture and Food Systems: Teacher Education Track (Under Construction) (NB)",
	"Major in Agriculture and Food Systems (NB)",
	"Major in American Studies (NB)",
	"Major in Animal Science, Preveterinary Medicine and Research Option (NB)",
	"Major in Animal Science, Companion Animal Science (NB)",
	"Major in Animal Science, Laboratory Animal Science Option (NB)",
	"Major in Animal Science, Equine and Production Animal Science (NB)",
	"Major in Cultural Anthropology (NB)",
	"Major in Anthropology (NB)",
	"Major in Evolutionary Anthropology (NB)",
	"Major in Art (for the B.A.) (NB)",
	"Major in Visual Arts (for the B.F.A.) (NB)",
	"Major in Art History (NB)",
	"Major in Asian Studies (NB)",
	"Major in Astrophysics (NB)",
	"Major in Biochemistry - Biochemistry of Microbial Systems Option (NB)",
	"Major in Biochemistry - Biochemical Toxicology Option (NB)",
	"Major in Biochemistry - Biochemistry of Plant Systems Option (NB)",
	"Major in Biochemistry - Protein and Structural Biochemistry Option (NB)",
	"Major in Biochemistry - General Option (NB)",
	"Major in Biological Sciences (Biology) (NB)",
	"Major in Biomathematics (NB)",
	"Major in Biotechnology, Bioscience Policy and Management Option (NB)",
	"Major in Biotechnology, Microbial Biotechnology Option (NB)",
	"Major in Biotechnology, Bioinformatics Option (NB)",
	"Major in Biotechnology, Plant Biotechnology Option (NB)",
	"Major in Biotechnology, Animal Biotechnology Option (NB)",
	"Major in Biotechnology, General Biotechnology Option (NB)",
	"Major in Business Analytics and Information Technology (BAIT) (NB)",
	"Major in Cell Biology and Neuroscience - Honors (NB)",
	"Major in Cell Biology and Neuroscience (NB)",
	"Major in Chemistry, Chemical Biology Option (C) (NB)",
	"Major in Chemistry, Environmental Option (D) (NB)",
	"Major in Chemistry, Business - Law Option (E) (NB)",
	"Major in Chemistry, Chemical Physics Option (F) (NB)",
	"Major in Chemistry, General ACS Option (G) (NB)",
	"Major in Chemistry, Core Option (NB)",
	"Major in Chemistry, Forensic Chemistry Option (M) (NB)",
	"Major in Chinese (NB)",
	"Major in Cinema Studies (NB)",
	"Major in Cognitive Science (NB)",
	"Major in Classics, Greek Option (NB)",
	"Major in Classics, Greek and Latin Option (NB)",
	"Major in Classics, Latin Option (NB)",
	"Major in Classics, Classical Humanities Option (NB)",
	"Major in Communication - Specialization in Health and Wellness Communication (NB)",
	"Major in Communication (NB)",
	"Major in Communication - Specialization in Leadership in Organizations and Community (NB)",
	"Major in Communication - Specialization in Strategic Public Communication and Public Relations (NB)",
	"Major in Communication - Specialization in Relationships and Family Communication (NB)",
	"Major in Communication - Specialization in Communication and Technology (NB)",
	"Major in Comparative Literature - Option in Advanced Studies in Comparative Literature (NB)",
	"Major in Comparative Literature (NB)",
	"Major in Computer Science - B.A. (NB)",
	"Major in Computer Science - B.S. (NB)",
	"Major in Criminal Justice (NB)",
	"Major in Criminal Justice (Off-Campus)",
	"Major in Dance (for the B.A.) (NB)",
	"Major in Dance (for the B.F.A.) (NB)",
	"Major in Dance - Dance Science Concentration (for the B.F.A.) (NB)",
	"Major in Design (for the B.F.A.) (NB)",
	"Major in Filmmaking (for the B.F.A.) (NB)",
	"Major in Ecology, Evolution and Natural Resources - Urban Forestry Option (NB)",
	"Major in Ecology, Evolution and Natural Resources (NB)",
	"Major in Ecology, Evolution and Natural Resources - Nat Res & Ecosystem Mgmt Option (NB)",
	"Major in Data Science - Chemical Data Science Option B.S. (NB)",
	"Major in Data Science - Economics Option B.S. (NB)",
	"Major in Data Science - Societal Impact Option B.A. (NB)",
	"Major in Data Science - Computer Science Option B.S. (NB)",
	"Major in Data Science - Statistics Option B.A. (NB)",
	"Major in Economics (NB)",
	"Major in English (NB)",
	"Major in European Studies (NB)",
	"Major in Entomology (NB)",
	"Major in Environmental and Business Economics, Environmental and Natural Resource Economics Option (NB)",
	"Major in Environmental and Business Economics, Food Industry Economics Option (NB)",
	"Major in Environmental and Business Economics, Business Economics Option (NB)",
	"Major in Environmental and Business Economics, Food Science and Management Economics (NB)",
	"Major in Environmental Policy, Institutions and Behavior (EPIB) (NB)",
	"Major in Environmental Sciences, Environmental Health Option (NB)",
	"Major in Environmental Sciences, Environmental Science Option (NB)",
	"Major in Environmental Sciences, Applied Environmental Science Option (NB)",
	"Major in Exercise Science (NB)",
	"Major in Exercise Science - Pre-Physical Therapy (NB)",
	"Major in Environmental Studies (NB)",
	"Major in Finance - Fixed Income and Credit Analysis Option (NB)",
	"Major in Finance (NB)",
	"Major in Food Science, One Pathway (NB)",
	"Major in French- Interdisciplinary (NB)",
	"Major in French (NB)",
	"Major in Genetics (NB)",
	"Major in Geography (NB)",
	"Major in Earth and Planetary Sciences, Environmental Geology Option (NB)",
	"Major in Earth and Planetary Sciences, Geological Sciences Option (NB)",
	"Major in Earth and Planetary Sciences, General Option (NB)",
	"Major in Earth and Planetary Sciences, Planetary Science Option (NB)",
	"Major in German (NB)",
	"Major in Health Administration - Direct Admits Option (NB)",
	"Major in Health Administration (NB)",
	"Major in History, Ancient History and Classics Option (NB)",
	"Major in History (NB)",
	"Major in History - French (NB)",
	"Major in History - Political Science (NB)",
	"Major in Human Resource Management - Honors (NB)",
	"Major in Human Resource Management (NB)",
	"Major in Information Technology and Informatics (ITI) (NB)",
	"Major in Landscape Architecture (NB)",
	"Major in Interdisciplinary Studies-SEBS (NB)",
	"Major in Italian Studies (NB)",
	"Major in Italian (NB)",
	"Major in Jewish Studies (NB)",
	"Major in Jewish Studies - Advanced Language Option (NB)",
	"Major in Japanese (NB)",
	"Major in Journalism and Media Studies - Specialization in Global Media (NB)",
	"Major in Journalism and Media Studies (NB)",
	"Major in Journalism and Media Studies - Specialization in Sports Journalism (NB)",
	"Major in Environmental Planning(NB)",
	"Major in Korean (NB)",
	"Major in Labor Studies and Employment Relations (NB)",
	"Major in Labor and Employment Relations (NB)",
	"Major in Labor and Employment Relations Online (NB)",
	"Major in Labor and Employment Relations Online (NB)",
	"Major in Latin American Studies (NB)",
	"Major in Latino and Caribbean Studies (NB)",
	"Major in Leadership and Management (NB)",
	"Major in Linguistics with Certificate in Speech and Hearing Sciences (NB)",
	"Major in Linguistics (NB)",
	"Major in Marine Sciences, Marine Chemistry Option (NB)",
	"Major in Marine Sciences, Marine Geology Option (NB)",
	"Major in Marine Sciences, Physical Oceanography Option (NB)",
	"Major in Marine Sciences, Directed Marine Studies Option (NB)",
	"Major in Marine Sciences, Marine Biology - Biological Oceanography Option (NB)",
	"Major in Marketing (NB)",
	"Major in Marketing with Certification in Professional Selling (NB)",
	"Major in Mathematics (NB)",
	"Major in Mathematics, Actuarial Option (NB)",
	"Major in Medieval Studies (NB)",
	"Major in Meteorology (NB)",
	"Major in Microbiology (NB)",
	"Major in Middle Eastern Studies (NB)",
	"Major in Middle Eastern Studies (NB)",
	"Major in Molecular Biology and Biochemistry (MBB) (NB)",
	"Major in Music (for the B.A.) (NB)",
	"Major in Music - Composition Option (NB)",
	"Major in Music - Music Education Instrumental Option (NB)",
	"Major in Music - Performance - Instrumental Option (NB)",
	"Major in Music - Performance - Voice Option (NB)",
	"Major in Music - Music Education Vocal General - Voice Option (NB)",
	"Major in Music - Jazz Option (NB)",
	"Major in Ecology, Evolution and Natural Resources (NB)",
	"Major in Nursing - Blackwood Program (NB)",
	"Major in Nursing - Accelerated Bachelor of Science in Nursing (ABS) for Students Who Have a Bachelor's Degree (NB)",
	"Major in Nursing (NB)",
	"Major in Nursing - RN-BS Degree (NB)",
	"Major in Nutritional Sciences, Dietetics Option (NB)",
	"Major in Nutritional Sciences, Food Service Administration Option (NB)",
	"Major in Nutritional Sciences, Community Nutrition Option (NB)",
	"Major in Nutritional Sciences - Pre-Dietetic (NB)",
	"Major in Nutritional Sciences, Biomedical Nutrition Option (NB)",
	"Major in Nutritional Sciences - Pre-Nutritional Sciences (NB)",
	"Major in Pharmacy (NB)",
	"Major in Philosophy (NB)",
	"Major in Physics - Professional Option (NB)",
	"Major in Physics - Engineering Dual Degree Option (NB)",
	"Major in Physics - General Option (NB)",
	"Major in Physics - Planetary Option (NB)",
	"Major in Physics, Applied Option (NB)",
	"Major in Planning and Public Policy - Direct Admits Option (NB)",
	"Major in Plant Science, Plant Agriculture and Horticulture (NB)",
	"Major in Plant Science, Natural Products (NB)",
	"Major in Plant Science, General Plant Biology Option (NB)",
	"Major in Political Science (NB)",
	"Major in Supply Chain Management (NB)",
	"Major in Portuguese (NB)",
	"Major in Psychology - Honors (NB)",
	"Major in Psychology (NB)",
	"Major in Public Health - Direct Admits Option (NB)",
	"Major in Public Health (NB)",
	"Major in Public Policy - Direct Admits Option (NB)",
	"Major in Public Policy (NB)",
	"Major in Religion (NB)",
	"Major in Russian (NB)",
	"Major in Social Work (NB)",
	"Major in Sociology (NB)",
	"Major in Spanish - Spanish Intensive Option (NB)",
	"Major in Spanish (NB)",
	"Major in Sport Management (NB)",
	"Major in Statistics (NB)",
	"Major in Statistics - Mathematics (NB)",
	"Major in Theater Arts (for the B.A.) (NB)",
	"Major in Theater Arts - Acting Concentration (for the B.F.A.) (NB)",
	"Major in Theater Arts - Acting Concentration (for the B.F.A.) (NB)",
	"Major in Theater Arts - Costume Technology Concentration (for the B.F.A.) (NB)",
	"Major in Theater Arts - Lighting Design Concentration (for the B.F.A.) (NB)",
	"Major in Theater Arts - Stage Management Concentration (for the B.F.A.) (NB)",
	"Major in Theater Arts - Costume Design Concentration (for the B.F.A.) (NB)",
	"Major in Theater Arts - Technical Direction Concentration (for the B.F.A.) (NB)",
	"Major in Theater Arts - Set Design Concentration (for the B.F.A.) (NB)",
	"Major in Theater Arts - Dramaturgy Concentration (for the B.F.A.) (NB)",
	"Major in Urban Planning and Design - Direct Admits Option (NB)",
	"Major in Urban Planning and Design (NB)",
	"Major in Women's and Gender Studies (NB)"
];

function cleanStrings(strings) {
	return strings.map(s => s.replace(/^Major in /, "").replace(/\s*\(.*\)$/, ""));
}
console.log(cleanStrings(res));

res = [
	"Accounting",
	"Global Humanities",
	"African, Middle Eastern and South Asian Languages and Literatures",
	"Africana Studies",
	"Agriculture and Food Systems",
	"Agriculture and Food Systems: Teacher Education Track",
	"Agriculture and Food Systems",
	"American Studies",
	"Animal Science, Preveterinary Medicine and Research Option",
	"Animal Science, Companion Animal Science",
	"Animal Science, Laboratory Animal Science Option",
	"Animal Science, Equine and Production Animal Science",
	"Cultural Anthropology",
	"Anthropology",
	"Evolutionary Anthropology",
	"Art",
	"Visual Arts",
	"Art History",
	"Asian Studies",
	"Astrophysics",
	"Biochemistry - Biochemistry of Microbial Systems Option",
	"Biochemistry - Biochemical Toxicology Option",
	"Biochemistry - Biochemistry of Plant Systems Option",
	"Biochemistry - Protein and Structural Biochemistry Option",
	"Biochemistry - General Option",
	"Biological Sciences",
	"Biomathematics",
	"Biotechnology, Bioscience Policy and Management Option",
	"Biotechnology, Microbial Biotechnology Option",
	"Biotechnology, Bioinformatics Option",
	"Biotechnology, Plant Biotechnology Option",
	"Biotechnology, Animal Biotechnology Option",
	"Biotechnology, General Biotechnology Option",
	"Business Analytics and Information Technology",
	"Cell Biology and Neuroscience - Honors",
	"Cell Biology and Neuroscience",
	"Chemistry, Chemical Biology Option",
	"Chemistry, Environmental Option",
	"Chemistry, Business - Law Option",
	"Chemistry, Chemical Physics Option",
	"Chemistry, General ACS Option",
	"Chemistry, Core Option",
	"Chemistry, Forensic Chemistry Option",
	"Chinese",
	"Cinema Studies",
	"Cognitive Science",
	"Classics, Greek Option",
	"Classics, Greek and Latin Option",
	"Classics, Latin Option",
	"Classics, Classical Humanities Option",
	"Communication - Specialization in Health and Wellness Communication",
	"Communication",
	"Communication - Specialization in Leadership in Organizations and Community",
	"Communication - Specialization in Strategic Public Communication and Public Relations",
	"Communication - Specialization in Relationships and Family Communication",
	"Communication - Specialization in Communication and Technology",
	"Comparative Literature - Option in Advanced Studies in Comparative Literature",
	"Comparative Literature",
	"Computer Science - B.A.",
	"Computer Science - B.S.",
	"Criminal Justice",
	"Criminal Justice",
	"Dance",
	"Dance",
	"Dance - Dance Science Concentration",
	"Design",
	"Filmmaking",
	"Ecology, Evolution and Natural Resources - Urban Forestry Option",
	"Ecology, Evolution and Natural Resources",
	"Ecology, Evolution and Natural Resources - Nat Res & Ecosystem Mgmt Option",
	"Data Science - Chemical Data Science Option B.S.",
	"Data Science - Economics Option B.S.",
	"Data Science - Societal Impact Option B.A.",
	"Data Science - Computer Science Option B.S.",
	"Data Science - Statistics Option B.A.",
	"Economics",
	"English",
	"European Studies",
	"Entomology",
	"Environmental and Business Economics, Environmental and Natural Resource Economics Option",
	"Environmental and Business Economics, Food Industry Economics Option",
	"Environmental and Business Economics, Business Economics Option",
	"Environmental and Business Economics, Food Science and Management Economics",
	"Environmental Policy, Institutions and Behavior",
	"Environmental Sciences, Environmental Health Option",
	"Environmental Sciences, Environmental Science Option",
	"Environmental Sciences, Applied Environmental Science Option",
	"Exercise Science",
	"Exercise Science - Pre-Physical Therapy",
	"Environmental Studies",
	"Finance - Fixed Income and Credit Analysis Option",
	"Finance",
	"Food Science, One Pathway",
	"French- Interdisciplinary",
	"French",
	"Genetics",
	"Geography",
	"Earth and Planetary Sciences, Environmental Geology Option",
	"Earth and Planetary Sciences, Geological Sciences Option",
	"Earth and Planetary Sciences, General Option",
	"Earth and Planetary Sciences, Planetary Science Option",
	"German",
	"Health Administration - Direct Admits Option",
	"Health Administration",
	"History, Ancient History and Classics Option",
	"History",
	"History - French",
	"History - Political Science",
	"Human Resource Management - Honors",
	"Human Resource Management",
	"Information Technology and Informatics",
	"Landscape Architecture",
	"Interdisciplinary Studies-SEBS",
	"Italian Studies",
	"Italian",
	"Jewish Studies",
	"Jewish Studies - Advanced Language Option",
	"Japanese",
	"Journalism and Media Studies - Specialization in Global Media",
	"Journalism and Media Studies",
	"Journalism and Media Studies - Specialization in Sports Journalism",
	"Environmental Planning",
	"Korean",
	"Labor Studies and Employment Relations",
	"Labor and Employment Relations",
	"Labor and Employment Relations Online",
	"Labor and Employment Relations Online",
	"Latin American Studies",
	"Latino and Caribbean Studies",
	"Leadership and Management",
	"Linguistics with Certificate in Speech and Hearing Sciences",
	"Linguistics",
	"Marine Sciences, Marine Chemistry Option",
	"Marine Sciences, Marine Geology Option",
	"Marine Sciences, Physical Oceanography Option",
	"Marine Sciences, Directed Marine Studies Option",
	"Marine Sciences, Marine Biology - Biological Oceanography Option",
	"Marketing",
	"Marketing with Certification in Professional Selling",
	"Mathematics",
	"Mathematics, Actuarial Option",
	"Medieval Studies",
	"Meteorology",
	"Microbiology",
	"Middle Eastern Studies",
	"Middle Eastern Studies",
	"Molecular Biology and Biochemistry",
	"Music",
	"Music - Composition Option",
	"Music - Music Education Instrumental Option",
	"Music - Performance - Instrumental Option",
	"Music - Performance - Voice Option",
	"Music - Music Education Vocal General - Voice Option",
	"Music - Jazz Option",
	"Ecology, Evolution and Natural Resources",
	"Nursing - Blackwood Program",
	"Nursing - Accelerated Bachelor of Science in Nursing",
	"Nursing",
	"Nursing - RN-BS Degree",
	"Nutritional Sciences, Dietetics Option",
	"Nutritional Sciences, Food Service Administration Option",
	"Nutritional Sciences, Community Nutrition Option",
	"Nutritional Sciences - Pre-Dietetic",
	"Nutritional Sciences, Biomedical Nutrition Option",
	"Nutritional Sciences - Pre-Nutritional Sciences",
	"Pharmacy",
	"Philosophy",
	"Physics - Professional Option",
	"Physics - Engineering Dual Degree Option",
	"Physics - General Option",
	"Physics - Planetary Option",
	"Physics, Applied Option",
	"Planning and Public Policy - Direct Admits Option",
	"Plant Science, Plant Agriculture and Horticulture",
	"Plant Science, Natural Products",
	"Plant Science, General Plant Biology Option",
	"Political Science",
	"Supply Chain Management",
	"Portuguese",
	"Psychology - Honors",
	"Psychology",
	"Public Health - Direct Admits Option",
	"Public Health",
	"Public Policy - Direct Admits Option",
	"Public Policy",
	"Religion",
	"Russian",
	"Social Work",
	"Sociology",
	"Spanish - Spanish Intensive Option",
	"Spanish",
	"Sport Management",
	"Statistics",
	"Statistics - Mathematics",
	"Theater Arts",
	"Theater Arts - Acting Concentration",
	"Theater Arts - Acting Concentration",
	"Theater Arts - Costume Technology Concentration",
	"Theater Arts - Lighting Design Concentration",
	"Theater Arts - Stage Management Concentration",
	"Theater Arts - Costume Design Concentration",
	"Theater Arts - Technical Direction Concentration",
	"Theater Arts - Set Design Concentration",
	"Theater Arts - Dramaturgy Concentration",
	"Urban Planning and Design - Direct Admits Option",
	"Urban Planning and Design",
	"Women's and Gender Studies"
];

a = new Set([
	"01:070:100",
	"01:070:101",
	"01:070:102",
	"01:070:104",
	"01:070:105",
	"01:070:108",
	"01:070:111",
	"01:070:112",
	"01:070:113",
	"01:070:152",
	"01:070:153",
	"01:070:161",
	"01:070:162",
	"01:070:163",
	"01:070:164",
	"01:070:170",
	"01:070:171",
	"01:070:201",
	"01:070:202",
	"01:070:203",
	"01:070:206",
	"01:070:207",
	"01:070:209",
	"01:070:212",
	"01:070:213",
	"01:070:215",
	"01:070:216",
	"01:070:217",
	"01:070:218",
	"01:070:219",
	"01:070:220",
	"01:070:221",
	"01:070:222",
	"01:070:223",
	"01:070:224",
	"01:070:225",
	"01:070:226",
	"01:070:227",
	"01:070:228",
	"01:070:230",
	"01:070:238",
	"01:070:240",
	"01:070:242",
	"01:070:243",
	"01:070:244",
	"01:070:246",
	"01:070:248",
	"01:070:250",
	"01:070:252",
	"01:070:283",
	"01:070:284",
	"01:070:291",
	"01:070:292",
	"01:070:293",
	"01:070:294",
	"01:070:295",
	"01:070:296",
	"01:070:297",
	"01:070:298",
	"01:070:299",
	"01:070:302",
	"01:070:303",
	"01:070:304",
	"01:070:305",
	"01:070:306",
	"01:070:307",
	"01:070:308",
	"01:070:309",
	"01:070:311",
	"01:070:312",
	"01:070:313",
	"01:070:314",
	"01:070:316",
	"01:070:317",
	"01:070:318",
	"01:070:319",
	"01:070:320",
	"01:070:321",
	"01:070:322",
	"01:070:323",
	"01:070:324",
	"01:070:325",
	"01:070:326",
	"01:070:327",
	"01:070:328",
	"01:070:329",
	"01:070:330",
	"01:070:331",
	"01:070:332",
	"01:070:333",
	"01:070:334",
	"01:070:335",
	"01:070:336",
	"01:070:337",
	"01:070:338",
	"01:070:339",
	"01:070:340",
	"01:070:341",
	"01:070:342",
	"01:070:343",
	"01:070:344",
	"01:070:345",
	"01:070:346",
	"01:070:347",
	"01:070:348",
	"01:070:349",
	"01:070:350",
	"01:070:351",
	"01:070:352",
	"01:070:354",
	"01:070:355",
	"01:070:356",
	"01:070:357",
	"01:070:358",
	"01:070:359",
	"01:070:360",
	"01:070:361",
	"01:070:362",
	"01:070:363",
	"01:070:365",
	"01:070:367",
	"01:070:368",
	"01:070:369",
	"01:070:370",
	"01:070:371",
	"01:070:372",
	"01:070:373",
	"01:070:374",
	"01:070:375",
	"01:070:376",
	"01:070:377",
	"01:070:378",
	"01:070:379",
	"01:070:380",
	"01:070:381",
	"01:070:382",
	"01:070:383",
	"01:070:384",
	"01:070:385",
	"01:070:386",
	"01:070:387",
	"01:070:388",
	"01:070:389",
	"01:070:390",
	"01:070:391",
	"01:070:392",
	"01:070:393",
	"01:070:394",
	"01:070:395",
	"01:070:396",
	"01:070:397",
	"01:070:398",
	"01:070:401",
	"01:070:402",
	"01:070:403",
	"01:070:404",
	"01:070:405",
	"01:070:406",
	"01:070:407",
	"01:070:408",
	"01:070:409",
	"01:070:410",
	"01:070:415",
	"01:070:417",
	"01:070:420",
	"01:070:422",
	"01:070:426",
	"01:070:486",
	"01:070:490",
	"01:070:491",
	"01:070:495",
	"01:070:496",
	"01:070:497",
	"01:070:498",
	"01:070:499",
	"01:070:EC",
	"01:070:EC1",
	"01:070:EC2",
	"01:070:MAJ",
	"01:070:NM",
	"01:070:302",
	"01:070:303",
	"01:070:304",
	"01:070:305",
	"01:070:306",
	"01:070:307",
	"01:070:308",
	"01:070:309",
	"01:070:311",
	"01:070:312",
	"01:070:313",
	"01:070:314",
	"01:070:316",
	"01:070:317",
	"01:070:318",
	"01:070:319",
	"01:070:320",
	"01:070:321",
	"01:070:322",
	"01:070:323",
	"01:070:324",
	"01:070:325",
	"01:070:326",
	"01:070:327",
	"01:070:328",
	"01:070:329",
	"01:070:330",
	"01:070:331",
	"01:070:332",
	"01:070:333",
	"01:070:334",
	"01:070:335",
	"01:070:336",
	"01:070:337",
	"01:070:338",
	"01:070:339",
	"01:070:340",
	"01:070:341",
	"01:070:342",
	"01:070:343",
	"01:070:344",
	"01:070:345",
	"01:070:346",
	"01:070:347",
	"01:070:348",
	"01:070:349",
	"01:070:350",
	"01:070:351",
	"01:070:352",
	"01:070:354",
	"01:070:355",
	"01:070:356",
	"01:070:357",
	"01:070:358",
	"01:070:359",
	"01:070:360",
	"01:070:361",
	"01:070:362",
	"01:070:363",
	"01:070:365",
	"01:070:367",
	"01:070:368",
	"01:070:369",
	"01:070:370",
	"01:070:371",
	"01:070:372",
	"01:070:373",
	"01:070:374",
	"01:070:375",
	"01:070:376",
	"01:070:377",
	"01:070:378",
	"01:070:379",
	"01:070:380",
	"01:070:381",
	"01:070:382",
	"01:070:383",
	"01:070:384",
	"01:070:385",
	"01:070:386",
	"01:070:387",
	"01:070:388",
	"01:070:389",
	"01:070:390",
	"01:070:391",
	"01:070:392",
	"01:070:393",
	"01:070:394",
	"01:070:395",
	"01:070:396",
	"01:070:397",
	"01:070:398",
	"01:070:401",
	"01:070:402",
	"01:070:403",
	"01:070:404",
	"01:070:405",
	"01:070:406",
	"01:070:407",
	"01:070:408",
	"01:070:409",
	"01:070:410",
	"01:070:415",
	"01:070:417",
	"01:070:420",
	"01:070:422",
	"01:070:426",
	"01:070:486",
	"01:070:490",
	"01:070:491",
	"01:070:495",
	"01:070:496",
	"01:070:497",
	"01:070:498",
	"01:070:499"
]);

const joinedString = [...a].map(item => `"${item}"`).join(", ");
joinedString;
